"""Protocol DSL, codecs, projection and rendering for multiparty sessions."""

from agentsparty.kernel.errors import CompositionError
from agentsparty.protocol._binding import associate
from agentsparty.protocol._conformance import subtype
from agentsparty.protocol.analysis import Duty, duties
from agentsparty.protocol.graph import GraphEdge, GraphNode, ProtocolGraph, to_graph  # noqa: WPS347
from agentsparty.protocol.language.core import (
    Case,
    Chosen,
    Codec,
    Deadline,
    Flag,
    Fragment,
    Integer,
    Label,
    Nothing,
    Null,
    Number,
    RawValue,
    Text,
    case,
    codec_of,
    dict_of,
    json_model,
    list_of,
    load_json,
    one_of,
    optional,
    record,
    refine,
    repeat,
    seq,
)
from agentsparty.protocol.language.endpoint import (
    EndpointBranch,
    EndpointBranchCase,
    EndpointEnd,
    EndpointFragment,
    EndpointRec,
    EndpointSelect,
    EndpointType,
    EndpointVar,
)
from agentsparty.protocol.render import render
from agentsparty.protocol.routine import Routine, do
from agentsparty.protocol.session import (
    Boundary,
    GlobalType,
    Interaction,
    Parallel,
    RecvFrom,
    SendTo,
    SessionBranchCase,
    SessionEnd,
    SessionFragment,
    SessionRec,
    SessionType,
    SessionVar,
    SingleSubject,
    alt,
    as_endpoint,
    as_global,
    as_session,
    assert_compatible,
    assert_wellformed,
    compose,
    ensure_session,
    epart,
    equal_session,
    ipart,
    localise,
    may_terminate,
    msg,
    must_terminate,
    owning,
    par,
    participants,
    project,
    project_all,
    project_onto,
    rec,
    stop,
    var,
)

__all__ = [
    'Boundary',
    # endpoint types (the DSL that builds them lives in agentsparty.protocol.language.endpoint —
    # its rec/var/stop collide with the session-level ones above)
    'Case',
    'Chosen',
    'Codec',
    'CompositionError',
    'Deadline',
    # common
    'Duty',
    'EndpointBranch',
    'EndpointBranchCase',
    'EndpointEnd',
    'EndpointFragment',
    'EndpointRec',
    'EndpointSelect',
    'EndpointType',
    'EndpointVar',
    'Flag',
    'Fragment',
    # session
    'GlobalType',
    'GraphEdge',
    'GraphNode',
    'Integer',
    'Interaction',
    'Label',
    # core / codecs
    'Nothing',
    'Null',
    'Number',
    'Parallel',
    'ProtocolGraph',
    'RawValue',
    'RecvFrom',
    # routine
    'Routine',
    'SendTo',
    'SessionBranchCase',
    'SessionEnd',
    'SessionFragment',
    'SessionRec',
    'SessionType',
    'SessionVar',
    'SingleSubject',
    'Text',
    'alt',
    'as_endpoint',
    'as_global',
    'as_session',
    'assert_compatible',
    # well-formedness and semantic equality
    'assert_wellformed',
    # subtype
    'associate',
    'case',
    'codec_of',
    'compose',
    'dict_of',
    'do',
    'duties',
    'ensure_session',
    'epart',
    'equal_session',
    'ipart',
    'json_model',
    'list_of',
    'load_json',
    'localise',
    'may_terminate',
    'msg',
    'must_terminate',
    'one_of',
    'optional',
    'owning',
    'par',
    'participants',
    'project',
    'project_all',
    'project_onto',
    'rec',
    'record',
    'refine',
    'render',
    'repeat',
    'seq',
    'stop',
    'subtype',
    'to_graph',
    'var',
]
